# Generated by Django 5.2 on 2025-04-25 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_materiel', models.CharField(choices=[('Ordinateur', 'Ordinateur'), ('Imprimante', 'Imprimante'), ('Serveur', 'Serveur'), ('Autre', 'Autre')], max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('numero_inventaire', models.CharField(max_length=100)),
                ('service_affectation', models.CharField(max_length=100)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('nom_deposant', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=100)),
                ('status', models.CharField(choices=[('Etudiant', 'Étudiant'), ('Ensiegnant', 'Enseignant'), ('Employer', 'Employé')], max_length=100)),
                ('panne_declaree', models.TextField()),
                ('status_demande', models.CharField(choices=[('Nouvelle', 'Nouvelle'), ('Acceptee', 'Acceptée'), ('Rejetee', 'Rejetée')], default='Nouvelle', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100)),
                ('priorite', models.CharField(choices=[('Haute', 'Haute'), ('Moyenne', 'Moyenne'), ('Basse', 'Basse')], max_length=100)),
                ('panne_trouvee', models.TextField()),
                ('composants_utilises', models.TextField()),
                ('status', models.CharField(choices=[('enCours', 'En Cours'), ('Termine', 'Terminé')], default='enCours', max_length=100)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('demande_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='base.demande')),
                ('technicien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
