# Generated by Django 5.1.7 on 2025-03-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=200)),
                ('numero_serie_eq', models.CharField(max_length=200)),
                ('numero_inventaire_eq', models.CharField(max_length=200)),
                ('designation', models.TextField()),
                ('observation', models.TextField(blank=True, null=True)),
                ('model_reference', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
