# Generated by Django 5.2 on 2025-04-24 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Composant',
            fields=[
                ('id_composant', models.AutoField(primary_key=True, serialize=False)),
                ('type_composant', models.CharField(choices=[('Nouveau', 'Nouveau'), ('Ancien', 'Ancien')], max_length=20)),
                ('model_reference', models.TextField(blank=True, null=True)),
                ('numero_serie', models.CharField(max_length=100)),
                ('designation', models.TextField()),
                ('observation', models.TextField(blank=True, null=True)),
                ('numero_serie_eq_source', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_inventaire_eq_source', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Used', 'Used'), ('Free', 'Free')], max_length=20, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.categorie')),
            ],
        ),
        migrations.DeleteModel(
            name='Component',
        ),
    ]
