# Generated by Django 5.2.1 on 2025-05-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='numero_inventaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
