# Generated by Django 5.2 on 2025-04-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_categorie_composant_delete_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composant',
            name='disponible',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
