# Generated by Django 5.2.1 on 2025-05-18 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_demande_numero_inventaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composant',
            name='categorie',
        ),
    ]
