# Generated by Django 5.2 on 2025-04-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_composant_disponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id_equipement', models.AutoField(primary_key=True, serialize=False)),
                ('model_reference', models.TextField(blank=True, null=True)),
                ('numero_serie', models.CharField(max_length=100)),
                ('designation', models.TextField()),
                ('observation', models.TextField(blank=True, null=True)),
                ('numero_inventaire', models.CharField(max_length=100)),
            ],
        ),
    ]
