# Generated by Django 5.2 on 2025-04-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_intervention_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
