# Generated by Django 5.2 on 2025-05-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_composant_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composant',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='composant',
            name='status',
            field=models.CharField(blank=True, choices=[('Used', 'Used'), ('Free', 'Free')], default='Free', max_length=20, null=True),
        ),
    ]
