# Generated by Django 5.2 on 2025-05-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_composant_quantity_alter_composant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='composant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_composants/'),
        ),
    ]
