# Generated by Django 5.2 on 2025-05-18 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_composant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composant',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0)),
        ),
    ]
